Issue 100 industry standards
ACWIC/training-provider-admin pull request #16
Opened 2020-11-15 11:21 UTC by TheAyeshaSiddiqa

2020-11-15 14:00 UTC, BarisSari requested changes
Thanks for the PR, @TheAyeshaSiddiqa. I asked for minor changes. After that, I'm going to approve it.

2020-11-16 07:41 UTC, TheAyeshaSiddiqa commented on app/domain/entities/industry_standard.py
> +    description: str
yeah good idea!

2020-11-27 07:35 UTC, BarisSari commented
It seems like there are many missing lines, @TheAyeshaSiddiqa. Can you implement API tests for new endpoints?

2020-11-27 07:38 UTC, TheAyeshaSiddiqa commented
> It seems like there are many missing lines, @TheAyeshaSiddiqa. Can you implement API tests for new endpoints?

Sure, I can.

2020-11-30 01:29 UTC, monkeypants approved these changes
codecov has a few niggles but otherwise LGTM

2020-11-30 01:30 UTC, monkeypants commented
I'll force this in (with coverage drop) and leave the branch open for more tests.

2020-11-30 01:30 UTC, merged